name: Angular CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Build
        run: npm run build -- --prod
      - name: Run tests
        run: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
